#!/bin/sh -f

#set -x

build_no_gl=no

build_args=
while test $# -ge 1 ; do
  case $1 in
    -no_gl) build_no_gl=yes;;
         *) build_args="${build_args} $1";;
  esac
  shift
done


. ../mgr/build_header

if [ ${build_compile} = "yes" ] ; then

cfiles="${cfiles} ./source/gl2ps.c"

if [ ${build_no_gl} = "yes" ] ; then
  ccflags="${ccflags} -DOUREX_GL2PS_NO_GL"
  ccflags="${ccflags} -I../../inlib"
fi

if [ ${build_visual} = "yes" ] ; then
  ccflags="${ccflags} /I."
  ccflags="${ccflags} /wd4996"
else
  ccflags="${ccflags} -I."
fi

ccflags="${ccflags} -I../zlib/include"

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
