#!/bin/sh 

file=debug0.cpp

/bin/rm -f ./cl_exe_tmp
eval cl.exe /nologo /EHsc ${file} > ./cl_exe_tmp
use_status=$?;if [ ${use_status} != 0 ] ; then cat ./cl_exe_tmp;/bin/rm -f ./cl_exe_tmp;exit ${use_status}; fi
/bin/rm -f ./cl_exe_tmp

echo debug_end
