#!/bin/sh -f

app_dir=`dirname $0`
app="`dirname ${app_dir}`"
app="`dirname ${app}`"
app="`basename ${app}`"
#echo ${app}

run_host="0.0.0.0"
run_port="9090"

run_gdb=no

args=""
while test $# -ge 1 ; do
  case $1 in
    -gdb) run_gdb=yes;;
    -host) if [ $# -ge 2 ] ; then
             shift;run_host=$1
           else         
             echo "-host <host id>"
             exit
           fi
           ;;
    -port) if [ $# -ge 2 ] ; then
             shift;run_port=$1
           else         
             echo "-port <uint>"
             exit
           fi
           ;;
     *) args="${args} $1";;
  esac
  shift
done

if [ "`uname -n | grep lal.in2p3.fr | grep lx`" != "" ] ; then on_lal_lx=yes;else on_lal_lx=no; fi
if [ "`uname -n`" = "clrlsstweb.in2p3.fr" ] ; then on_clrlsst=yes;else on_on_clrlsst=no; fi

if [ "${on_lal_lx}" = "yes" ] ; then
  wt_home=/exp/si/barrand/usr/local/wt/3.2.3
  wt_doc="${wt_home}/share/Wt"
else
  wt_home=/usr/local/wt/3.2.3
  wt_doc="${wt_home}/share/Wt"
fi

if [ ! -d ${wt_home} ] ; then
  wt_home=/tmp/${app}_wt
  /bin/rm -R -f ${wt_home}
  wt_doc="${wt_home}/share/Wt"
  /bin/mkdir -p ${wt_doc}/exlib_tmp
fi

if [ ! -d ${wt_home} ] ; then
  echo "directory ${wt_home} not found."
  exit
fi

if [ ! -d ${wt_doc}/exlib_tmp ] ; then
  echo "directory ${wt_doc}/exlib_tmp not found."
  exit
fi

if [ `uname` = Darwin ] ; then
  export DYLD_LIBRARY_PATH=${wt_home}/lib
  #export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:/usr/local/boost/1.52.0/lib"
fi

# WARNING : exlib/Wt/render will create files under :
#             <docroot>/exlib_tmp
#           Then it must be an existing writeable directory.
args="${args} --docroot ${wt_doc}"

if [ "${on_lal_lx}" = "yes" ] ; then
  args="${args} --http-address 134.158.91.15"
  args="${args} --http-port 9090"
elif [ "${on_clrlsst}" = "yes" ] ; then
  args="${args} --http-address 193.48.81.110"
  args="${args} --http-port 54123"
else
  args="${args} --http-address ${run_host}"
  args="${args} --http-port ${run_port}"
fi

# NOTE : if wanting to upload big data file, you have to change in :
#          ../res/wt_config.xml
#        the resource :
#	       <max-request-size>
#        which is at 128 (128*1024 bytes) by default.

if [ -f ${app_dir}/../res/wt_config.xml ] ; then
  args="${args} --approot ${app_dir}/../res"
fi

args="${args} -land" #nemoview specific

${app_dir}/${app} ${args}

find ${wt_home}/share/Wt/exlib_tmp -name 'exlib_*' -type f -exec /bin/rm -f {} \;
