#!/bin/sh -f

if [ $# -le 0 ] ; then
 save_dir=`pwd`
 cd ../../..
 pwd
 find . -name '*.license' -exec ${save_dir}/update_apps_license ${save_dir} {} \;
 cd ${save_dir}
 exit
fi

exlib_mgr=$1
license_path=$2

app_name=`basename ${license_path} | sed -e 's:.license::g'`

#echo ${exlib_mgr}
echo ${license_path}
echo ${app_name}

/bin/cp ${exlib_mgr}/app_license ./tmp_0
sed -e "s:xxxx:${app_name}:g" ./tmp_0 > ${license_path}
/bin/rm -f ./tmp_0
