#!/bin/sh -f

from=/Users/barrand/private/dev/data/wrl
to=/Users/barrand/Documents/ioda/.

items="sarah couch dog piano2 plant computer"

exe=./bin_sdk_mac/iv2exsg

for item in ${items} ; do
  #echo $item
  ${exe} -bsg -scale=1000 ${from}/${item}.wrl
  /bin/mv out.bsg ${to}/LHCb_avatar_${item}.bsg
done
