#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

if [ ${build_compile} = "yes" ] ; then

if [ ${build_visual} = "yes" ] ; then
  cfiles="${cfiles} ./src/builds/win32/ftsystem.c"
else
  cfiles="${cfiles} ./src/builds/unix/ftsystem.c"
fi

cfiles="${cfiles} ./src/base/ftdebug.c"
cfiles="${cfiles} ./src/base/ftinit.c"
cfiles="${cfiles} ./src/base/ftbase.c"
cfiles="${cfiles} ./src/base/ftbbox.c"
cfiles="${cfiles} ./src/base/ftbdf.c"
cfiles="${cfiles} ./src/base/ftglyph.c"
cfiles="${cfiles} ./src/base/ftmm.c"
cfiles="${cfiles} ./src/base/ftpfr.c"
cfiles="${cfiles} ./src/base/ftstroke.c"
cfiles="${cfiles} ./src/base/fttype1.c"
cfiles="${cfiles} ./src/base/ftwinfnt.c"

cfiles="${cfiles} ./src/base/ftxf86.c"
cfiles="${cfiles} ./src/gzip/ftgzip.c"
cfiles="${cfiles} ./src/autohint/autohint.c"
cfiles="${cfiles} ./src/bdf/bdf.c"
cfiles="${cfiles} ./src/cache/ftcache.c"
cfiles="${cfiles} ./src/cff/cff.c"
cfiles="${cfiles} ./src/cid/type1cid.c"
cfiles="${cfiles} ./src/lzw/ftlzw.c"
cfiles="${cfiles} ./src/pcf/pcf.c"
cfiles="${cfiles} ./src/pfr/pfr.c"
cfiles="${cfiles} ./src/psaux/psaux.c"
cfiles="${cfiles} ./src/pshinter/pshinter.c"
cfiles="${cfiles} ./src/psnames/psmodule.c"
cfiles="${cfiles} ./src/raster/raster.c"
cfiles="${cfiles} ./src/sfnt/sfnt.c"
cfiles="${cfiles} ./src/smooth/smooth.c"
cfiles="${cfiles} ./src/truetype/truetype.c"
cfiles="${cfiles} ./src/type1/type1.c"
cfiles="${cfiles} ./src/type42/type42.c"
cfiles="${cfiles} ./src/winfonts/winfnt.c"

if [ ${build_visual} = "yes" ] ; then
  ccflags="${ccflags} /wd4996"
fi

ccflags="${ccflags} -I./include"
ccflags="${ccflags} -I./include/freetype"
ccflags="${ccflags} -I./src/builds"

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
