#!/bin/sh -f

# we expect that the compiler command (with options) is passed in one arg.

platform=
if [ $# != 1 ] ; then
  echo ${platform}
  exit
fi

cpp_compiler="$1"

bin_path=`dirname $0`

save_dir=`pwd`
cd ${bin_path}

if [ "`uname | grep CYGWIN`" != "" ] ; then
  cppflags="/nologo /DWIN32 /MD /O2 /W3 /EHsc /GR" 
  #NOTE : cl.exe prints the name of the compiled source file.
  #       We remove this output by sending it to /dev/null.
  ${cpp_compiler} ${cppflags} /I.. ../apps/platform.cpp 1> /dev/null
  platform="`./platform.exe`"
  platform="`echo ${platform} | sed -e 's: :\\\ :g'`"
  /bin/rm -f ./platform.obj ./platform.exe ./platform.exe.manifest
else
  ${cpp_compiler} -o inlib_platform -I.. ../apps/platform.cpp
  platform=`./inlib_platform`
  /bin/rm -f ./inlib_platform
fi

cd ${save_dir}

echo ${platform}
