#!/bin/sh -f

if [ $# != 2 ] ; then
  echo 'find_rm : two arguments expected'
  exit
fi

#set -v 
#echo "debug $1"
#echo "debug $2"

find $1 -name $2 -print > ./tmp_find_rm
for file in $(cat ./tmp_find_rm) ; do
#  echo "find_rm : rm ${file}"
  /bin/rm -R -f ${file}
done
/bin/rm -f ./tmp_find_rm
