#!/bin/sh -f

if [ $# != 1 ] ; then
  echo 'give a directory path.'
  exit
fi

c++ -o c_count ../apps/c_count.c

/bin/rm -f ./tmp_0
find $1 -name '*' -type f -exec ./c_count {} \; | grep -v Total >& ./tmp_0
awk 'BEGIN{x=0;}{x+=$0;}END{print x}' ./tmp_0

/bin/rm -f ./tmp_0
/bin/rm -f c_count
