#!/bin/sh -f

bush_home=`pwd`/../../bush

save_dir=`pwd`

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////
${bush_home}/find_rm ../comres '*.*'
#/////////////////////////////////////////////////////////////
#/// get some files from ioda and put them in comres /////////
#/////////////////////////////////////////////////////////////

cd ..

from=../ioda/res
if [ ! -d ${from} ] ; then
  echo "directory ${from} not found"
  exit
fi

files=""
files="${files} arialbd.ttf helveticabd.ttf courbd.ttf lucidagrandebd.ttf" #gui fonts.
files="${files} helvetica.ttf"

# cam panel :
files="${files} move2red.jpg crazyeye_run.jpg flip_flop.jpg"
files="${files} close.jpg edit.jpg edit_undo.jpg"

# main gui :
files="${files} go_home_large.jpg turn_around.jpg"
files="${files} movie_camera.jpg system_config_boot.jpg"

# rwc items :
files="${files} sidebar_photos.jpg stop_diaporama.jpg"
files="${files} cursor.jpg"

# main menu :
files="${files} files.jpg"
files="${files} application_exit.jpg"
files="${files} connect_to_wall.jpg"
files="${files} edit_clear.jpg edit_undo.jpg"
files="${files} move2red.jpg flip_flop.jpg"
files="${files} object_rotate_left.jpg stop_object_rotate_left.jpg"
files="${files} document_export.jpg"
files="${files} routing_step.jpg console.jpg tools.jpg"

for file in ${files} ; do
  /bin/cp ${from}/${file} ./comres/.
done

/bin/cp ${from}/ioda.style ./comres/ArcheryTune.style
/bin/cp ${from}/ioda.wall ./comres/ArcheryTune.wall

/bin/cp ./icons/scope_128.jpg ./comres/scope.jpg
/bin/cp ./icons/plot_128.jpg ./comres/plot.jpg
/bin/cp ./icons/beos_menu.jpg ./comres/.

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////

files=""
files="${files} white.jpg"
files="${files} icon.jpg favicon.ico"

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

find ../nature -name '*.jpg' -print > find_tmp
for file in $(cat find_tmp) ; do
  low_file=`basename ${file}`
  low_file=`echo ${low_file} | tr "[:upper:]" "[:lower:]"`
  low_file=`echo ${low_file} | sed -e 's:-:_:g'`
  /bin/cp ${file} ../comres/${low_file}
done
/bin/rm -f ./find_tmp

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// Android : ///////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res

#/////////////////////////////////////////////////////////////
#/// iOS : ///////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

if [ -d ../icons ] ; then
  which=_no_back_plus_gros
  if [ -d ../iOS ] ; then
    cp ../icons/icon_57${which}.png ../iOS/Icon.png
    cp ../icons/icon_72${which}.png ../iOS/Icon-72.png
    cp ../icons/icon_114${which}.png ../iOS/Icon-114.png
  fi
fi

