#!/bin/sh -f

save_dir=`pwd`

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////
../../inexlib/inlib/mgr/find_rm ../comres '*.*'
#/////////////////////////////////////////////////////////////
#/// get some files from ioda and put them in comres /////////
#/////////////////////////////////////////////////////////////

cd ..

from=../ioda/res
if [ ! -d ${from} ] ; then
  echo "directory ${from} not found"
  exit
fi

files=""
files="${files} arialbd.ttf helvetica.ttf"

# cam panel :
files="${files} move2red.jpg crazyeye_run.jpg flip_flop.jpg"
files="${files} close.jpg edit.jpg edit_undo.jpg"

# main gui :
files="${files} go_home_large.jpg turn_around.jpg"
files="${files} movie_camera.jpg system_config_boot.jpg"

# rwc items :
files="${files} sidebar_photos.jpg stop_diaporama.jpg"
files="${files} cursor.jpg"

# main menu :
files="${files} files.jpg"
files="${files} application_exit.jpg"
files="${files} connect_to_wall.jpg"
files="${files} edit_clear.jpg edit_undo.jpg"
files="${files} move2red.jpg flip_flop.jpg"
files="${files} object_rotate_left.jpg"
files="${files} document_export.jpg"
files="${files} routing_step.jpg console.jpg tools.jpg"

for file in ${files} ; do
  /bin/cp ${from}/${file} ./comres/.
done

/bin/cp ${from}/ioda.style ./comres/ArcheryTune.style
/bin/cp ${from}/ioda.wall ./comres/ArcheryTune.wall

/bin/cp ./icons/scope_128.jpg ./comres/scope.jpg
/bin/cp ./icons/plot_128.jpg ./comres/plot.jpg
/bin/cp ./icons/beos_menu.jpg ./comres/.

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////

files=""
files="${files} white.jpg"
files="${files} icon.jpg"

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

find ../nature -name '*.jpg' -print > find_tmp
for file in $(cat find_tmp) ; do
  low_file=`basename ${file}`
  low_file=`echo ${low_file} | tr "[:upper:]" "[:lower:]"`
  low_file=`echo ${low_file} | sed -e 's:-:_:g'`
  /bin/cp ${file} ../comres/${low_file}
done
/bin/rm -f ./find_tmp

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

cd ..

tos="./Android/res/raw ./NativeAndroid/res/raw"

find ./comres -name '*' -type f -print > ./comres_tmp

for dir in ${tos} ; do
  if [ -d ${dir} ] ; then
    ${save_dir}/../../inexlib/inlib/mgr/find_rm "${dir}" '*_*'
    for file in $(cat ./comres_tmp) ; do
      name="`basename ${file}`"
      if [ ${dir} = "./Android/res/raw" ] ; then
        raw_file=`echo ${name} | sed -e 's:\.:_:g'`
        raw_file=`echo ${raw_file} | tr "[:upper:]" "[:lower:]"`
        /bin/cp ${file} ${dir}/${raw_file}
      elif [ ${dir} = "./NativeAndroid/res/raw" ] ; then
        raw_file=`echo ${name} | sed -e 's:\.:_:g'`
        raw_file=`echo ${raw_file} | tr "[:upper:]" "[:lower:]"`
        /bin/cp ${file} ${dir}/${raw_file}
      else
       /bin/cp ${file} ${dir}/.
      fi
    done
  fi
done
/bin/rm -f ./comres_tmp

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
which=_no_back_plus_gros

if [ -d ../icons ] ; then
  if [ -d ../Android/res ] ; then
    mkdir -p ../Android/res/drawable-ldpi
    mkdir -p ../Android/res/drawable-mdpi
    mkdir -p ../Android/res/drawable-hdpi

    cp ../icons/icon_36${which}.png ../Android/res/drawable-ldpi/icon.png
    cp ../icons/icon_48${which}.png ../Android/res/drawable-mdpi/icon.png
    cp ../icons/icon_72${which}.png ../Android/res/drawable-hdpi/icon.png
  fi
  if [ -d ../NativeAndroid/res ] ; then
    mkdir -p ../NativeAndroid/res/drawable-ldpi
    mkdir -p ../NativeAndroid/res/drawable-mdpi
    mkdir -p ../NativeAndroid/res/drawable-hdpi

    cp ../icons/icon_36${which}.png ../NativeAndroid/res/drawable-ldpi/icon.png
    cp ../icons/icon_48${which}.png ../NativeAndroid/res/drawable-mdpi/icon.png
    cp ../icons/icon_72${which}.png ../NativeAndroid/res/drawable-hdpi/icon.png
  fi
  if [ -d ../iOS ] ; then
    cp ../icons/icon_57${which}.png ../iOS/Icon.png
    cp ../icons/icon_72${which}.png ../iOS/Icon-72.png
    cp ../icons/icon_114${which}.png ../iOS/Icon-114.png
  fi
fi

