#!/bin/sh -f

inlib_mgr="`pwd`/../../inexlib/inlib/mgr"
exlib_mgr="`pwd`/../../inexlib/exlib/mgr"

app="`${inlib_mgr}/appname`"
version="`${inlib_mgr}/appvers`"

save_dir=`pwd`

cd ../..

inlib_incs=./inlib_incs
c++ -o ${inlib_incs} -I${inlib_mgr}/.. ${inlib_mgr}/../apps/incs.cpp
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

to=/tmp/${app}
/bin/rm -R -f /tmp/${app}
/bin/rm -f /tmp/${app}_source-${version}.zip

/bin/mkdir -p ${to}

#verbose=-verbose

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
dirs=./inexlib/inlib:./inexlib/exlib

nos='exlib/cbk/wall:wall_client'

configs="batch X11 Windows Android WebGL"
for config in ${configs} ; do
  /bin/rm -f ./tmp_0
  /bin/cp ${exlib_mgr}/../exlib/app/${config}/app_main_cpp ./tmp_0
  sed -e "s:EXLIB_APP:${app}:g" ./tmp_0 > ./${app}/mgr/main.cpp
  /bin/rm -f ./tmp_0
  ${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ./${app}/mgr/main.cpp
  /bin/cp ${exlib_mgr}/../exlib/app/${config}/app_main_cpp ${to}/inexlib/exlib/exlib/app/${config}/.
done

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ./${app}/Cocoa/main.mm
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ./${app}/Cocoa/GLView.mm
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ./${app}/iOS/Classes/GLView.mm

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ./inexlib/inlib/apps/platform.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ./inexlib/inlib/apps/windef.c

/bin/rm -f ${inlib_incs}
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/mkdir -p ${to}/inexlib/ourex

items="mgr"
items="${items} glutess freetype jpeg png csz expat gl2ps zlib"
for item in ${items} ; do
  /bin/cp -R ./inexlib/ourex/${item} ${to}/inexlib/ourex/.
done

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////

/bin/cp -R ./${app}/mgr ${to}/${app}/.
/bin/cp -R ./${app}/res ${to}/${app}/.
/bin/cp -R ./${app}/comres ${to}/${app}/.

/bin/cp -R ./${app}/Android ${to}/${app}/.

/bin/cp ./inexlib/exlib/exlib/app/Android/Main_java ${to}/inexlib/exlib/exlib/app/Android/.

/bin/cp -R ./${app}/Cocoa ${to}/${app}/.
/bin/cp -R ./${app}/iOS ${to}/${app}/.

/bin/cp -R ./inexlib/inlib/mgr ${to}/inexlib/inlib/.
/bin/cp -R ./inexlib/exlib/mgr ${to}/inexlib/exlib/.

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
${inlib_mgr}/find_rm ${to} 'bin_*'
${inlib_mgr}/find_rm ${to} 'CVS'
${inlib_mgr}/find_rm ${to} '.git'
${inlib_mgr}/find_rm ${to} '.DS_Store'
${inlib_mgr}/find_rm ${to} 'DerivedData'
${inlib_mgr}/find_rm ${to} 'out*_log'
${inlib_mgr}/find_rm ${to} 'err*_log'
${inlib_mgr}/find_rm ${to} 'out*.log'
${inlib_mgr}/find_rm ${to} 'out*.fits'
${inlib_mgr}/find_rm ${to} 'out*.ps'
${inlib_mgr}/find_rm ${to} 'out*.root'
${inlib_mgr}/find_rm ${to} '*.o'
${inlib_mgr}/find_rm ${to} 'term_*.hist'
${inlib_mgr}/find_rm ${to} 'secure.properties'

/bin/rm -R -f ${to}/${app}/Android/bin
/bin/rm -R -f ${to}/${app}/Android/gen
/bin/rm -R -f ${to}/${app}/Android/libs
/bin/rm -R -f ${to}/${app}/Android/obj

/bin/rm -R -f ${to}/${app}/Cocoa/build
/bin/rm -R -f ${to}/${app}/Cocoa/${app}.xcodeproj/project.xcworkspace
/bin/rm -R -f ${to}/${app}/Cocoa/${app}.xcodeproj/xcuserdata

/bin/rm -R -f ${to}/${app}/iOS/build
/bin/rm -R -f ${to}/${app}/iOS/${app}.xcodeproj/project.xcworkspace
/bin/rm -R -f ${to}/${app}/iOS/${app}.xcodeproj/xcuserdata

/bin/rm -f ${to}/${app}/mgr/inlib_platform

${inlib_mgr}/find_rm ${to}/${app}/mgr '*.zip'

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
if [ ${app} = ArcheryTune ] ; then
  sed -e 's:WALL_DATA_CLIENT:RM_WALL_DATA_CLIENT:g' ${to}/inexlib/exlib/mgr/build_header > ./tmp_0
  /bin/mv ./tmp_0 ${to}/inexlib/exlib/mgr/build_header
fi
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
cd ${to}/${app}/mgr
cd /tmp
zip -qr ./${app}_source-${version}.zip ${app}

cd ${save_dir}
