#!/bin/sh -f

# This script assumes that java and android sdk/ndk are available (then
# ndk-build, ant,... etc are available).

#///////////////////////////////////////////////
#///////////////////////////////////////////////
#///////////////////////////////////////////////
save_dir=`pwd`

cd ../mgr

exlib_mgr=../../inexlib/exlib/mgr
${exlib_mgr}/check_app ndk-build 'ndk-build program not found.'
build_status=$?;if [ ${build_status} != 0 ] ; then exit ${build_status};fi

app="`${exlib_mgr}/app_name`"

cd ${save_dir}

#///////////////////////////////////////////////
#///////////////////////////////////////////////
#///////////////////////////////////////////////

echo "NOTE : jks password is 'android'"

build_debug=no
build_verbose=no
build_set_x=no

build_ndk=yes
build_java=yes
build_sign=yes # due to a bug in SDK 22 and Android 2.2
build_install=yes

build_pwd=android

while test $# -ge 1 ; do
  case $1 in
    -g) build_debug=yes;;
    -x) build_set_x=yes;;
    -v) build_verbose=yes;;

    -java)    build_ndk=no;build_sign=no;build_install=no;;
    -install) build_ndk=no;build_java=no;build_sign=no;;
    -*) echo "unknown option : $1" ; exit ;;
  esac
  shift
done

if [ ${build_set_x} = "yes" ] ; then set -x; fi

#///////////////////////////////////////////////
#///////////////////////////////////////////////
#///////////////////////////////////////////////
from=../../inexlib/exlib/exlib/app/Android
to=./src/fr/in2p3/lal/${app}
/bin/rm -f tmp_0
sed -e "s:EXLIB_APP:${app}:g" ${from}/Native_Main_java > tmp_0
cp tmp_0 ${to}/Main.java
/bin/rm -f tmp_0
#///////////////////////////////////////////////
#///////////////////////////////////////////////
#///////////////////////////////////////////////

if [ ${build_ndk} = "yes" ] ; then
  if [ ${build_verbose} = "yes" ] ; then
    ndk-build V=1
  else
    ndk-build
  fi
fi

target=release
if [ ${build_debug} = "yes" ] ; then target=debug;fi

if [ ${build_java} = "yes" ] ; then  
  ant ${target}
  # due to a bug in SDK 22 and Android 2.2, we resign anyway.
fi

if [ ${build_sign} = "yes" ] ; then
  if [ ${build_debug} = "yes" ] ; then
    echo "don't know how to sign in debug mode."
  else 
    if [ ${build_verbose} = "yes" ] ; then
      echo "build : sign ..."
    fi

    /bin/cp ./bin/${app}-${target}-unsigned.apk ./bin/${app}-${target}-unaligned.apk
    jarsigner -keystore ./${app}.jks -storepass ${build_pwd} -keypass ${build_pwd} ./bin/${app}-${target}-unaligned.apk ${app}
    zipalign -f 4 ./bin/${app}-${target}-unaligned.apk ./bin/${app}-${target}.apk
  fi
fi

if [ ${build_install} = "yes" ] ; then
  adb install -r ./bin/${app}-${target}.apk
fi

cd ${save_dir}
