#!/bin/sh -f

data_dir=${HOME}/Documents/ioda

detector=
do_component=no
do_all=

camera=
projection=
gl2ps=
exsg=
write_dummy=
write_mem=
solid=no

args=""
while test $# -ge 1 ; do
  case $1 in
    -component) do_component=yes
        args="${args} $1"
        ;;
    -all) do_all=yes
        args="${args} $1"
        ;;
    -perspective) camera="-perspective"
        args="${args} $1"
        ;;
    -side) projection="-side"
        args="${args} $1"
        ;;
    -3D) projection="-3D"
        args="${args} $1"
        ;;
    -3D_back) projection="-3D_back"
        args="${args} $1"
        ;;
    -gl2ps) gl2ps="-gl2ps"
        args="${args} $1"
        ;;
    -exsg) exsg="-exsg"
        args="${args} $1"
        ;;
    -write_dummy) write_dummy="-write_dummy"
        args="${args} $1"
        ;;
    -write_mem) write_mem="-write_mem"
        args="${args} $1"
        ;;
    -solid) solid="yes"
        args="${args} $1"
        ;;
    -*) echo "unknown option : $1" ; exit ;;
     *) if [ $# = 1 ] ; then
          detector=$1
        else         
          echo "unknown option : $1"
        fi
        ;;
  esac
  shift
done

app=../examples/cpp/exlib_example_root_volume_X11

app="${app} ${camera} ${gl2ps} ${exsg} ${write_dummy} ${write_mem}"

if [ "${detector}" = "" ] ; then
  echo "no detector given."
fi

if [ "${detector}" = "lhcb" ] ; then
 file=${data_dir}/lhcbfull.root
else
 file=${data_dir}/${detector}.root
fi

if [ "${do_all}" = "yes" ] ; then
  if [ "${solid}" = "yes" ] ; then
    ${app} -black ${projection} -min_depth=0 -solid_depth=0 -max_depth=100 ${file}
  else
    ${app} -black ${projection} -min_depth=0 -solid_depth=100 -max_depth=100 ${file}
  fi
  exit
fi

# depths :
#  13 atlas 
#  9  lhcbfull
#  14 cms
#  10 babar
#  10 aleph
#  13 alice 
#

if [ "${detector}" = "cms" ] ; then
if [ "${do_component}" = "yes" ] ; then
  ${app} -black -vol='MY42' ${data_dir}/cms.root
else
  ${app} -black -min_depth=2 -solid_depth=5 -max_depth=6 -3D ${file}
fi
fi

if [ "${detector}" = "alice" ] ; then
if [ "${do_component}" = "yes" ] ; then
  # xtru :
  # ITSssdLay5Ladd, ITSssdLay6Ladd, ITSsuppSDDSideAExtTrayCover
  ${app} -3D -radius=80 -vol='ITSssdLay5Ladd' ${file}  # xtru
#  ${app} -3D -radius=1500 -vol='L3DoorR' ${file}       # xtru
#   ${app} -3D -radius=50 -vol='FOST' ${file}            # CylR
else
  #-radius=7000
  ${app} -black -3D -min_depth=2 -solid_depth=3 -max_depth=4 ${file}
#  ${app} -black -3D -min_depth=0 -solid_depth=0 -max_depth=4 ${file}
fi
fi

if [ "${detector}" = "lhcb" ] ; then
if [ "${do_component}" = "yes" ] ; then

  ${app} -black -radius=6500 ${projection} -vol='Rich2lvRich2SphMirrorRightHalfHexBotBHoleSeg' ${file}
#  ${app} -black -radius=6500 ${projection} -vol='Rich2lvRich2SphMirrorRightHalfHexSeg' ${file}

#  ${app} -black -radius=7000 -3D -vol='MagnetCoil' ${file}
#  ${app} -black -radius=7000 -3D  -light -vol='MagnetCoil' ${file}
#  ${app} -black -radius=7000 -3D  -vol='MagnetCoil' ${file}
else
  ${app} -black -radius=20000 ${projection} -min_depth=1 -solid_depth=4 -max_depth=5 ${file}
fi
fi

if [ "${detector}" = "atlas" ] ; then
if [ "${do_component}" = "yes" ] ; then
  ${app} -black -solid -radius=200 -max_shapes=100 ${projection} -vol='EGLU' ${file}  #gtrap
#  ${app} -black -radius=300 ${projection} -vol='XD18' ${file}
#  ${app} -black -radius=5000 ${projection} -vol='INNE' ${file}
#  ${app} -black -radius=5000 ${projection} -vol='ATLS' ${file}
else
  ${app} -black -radius=5000 -3D_back -min_depth=1 -solid_depth=4 -max_depth=5 ${file}
#  ${app} -black -radius=5000 -3D_back -min_depth=0 -solid_depth=0 -max_depth=7 ${file}
fi
fi

if [ "${detector}" = "aleph" ] ; then
if [ "${do_component}" = "yes" ] ; then
  ${app} -black -3D -vol='HBMO' ${file}
  ${app} -black -3D -vol='ECMO' ${file}

  ${app} -black -vol='EBMO' ${file}
  ${app} -black -vol='ECMO' ${file}
  ${app} -black -vol='HBMO' ${file}
  ${app} -black -vol='HCMO' ${file}
else
  ${app} -black -min_depth=2 -solid_depth=4 -max_depth=6 -3D ${file}
fi
fi

if [ "${detector}" = "babar" ] ; then
  ${app} -black -radius=500 -min_depth=2 -solid_depth=3 -max_depth=4 -3D ${file}
fi
